name: Hello World Training Workflow

on:
  # Dispara el workflow al hacer push a la rama 'main'
  push:
    branches: [ main ]
  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub
  workflow_dispatch:
  # Dispara el workflow cuando se abre o edita un issue (propuesta)
  issues:
    types: [opened, edited]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "John Doe"
    steps:
    - name: Greet the User
      run: echo "Hello World!"
    
    # List all files in the current directory for comparison before and after actions/checkout@v5.
    - run: ls -l
    
    - uses: actions/checkout@v5
    
    - run: ls -l
    
    - name: Run a multi-line script
      run: |
        echo "Custom Env variable: $MY_ENV"
        echo "Usuario autenticado $GITHUB_ACTOR"